from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Protocol


class CoreClient(Protocol):
    # Core runtime surface (thin client contract)
    def submit_text(self, source: str, text: str, client_meta: Optional[Dict[str, Any]] = None, trace_id: Optional[str] = None) -> str: ...
    def get_result(self, trace_id: str) -> Optional[Dict[str, Any]]: ...
    def get_status(self) -> Dict[str, Any]: ...

    def admin_unlock(self, passphrase: str) -> bool: ...
    def admin_lock(self) -> None: ...

    def request_sleep(self) -> None: ...
    def request_shutdown(self) -> None: ...
    def wake(self) -> str: ...
    def say(self, text: str, source: str = "system") -> str: ...
    def request_listen(self, source: str = "ui") -> str: ...

    def set_voice_enabled(self, enabled: bool) -> None: ...
    def set_wake_word_enabled(self, enabled: bool) -> None: ...

    def get_jobs_summary(self, limit: int = 50) -> List[Dict[str, Any]]: ...
    def cancel_job(self, job_id: str) -> bool: ...

    def get_recent_errors(self, n: int = 50) -> List[Dict[str, Any]]: ...
    def get_recent_security_events(self, n: int = 50) -> List[Dict[str, Any]]: ...
    def get_recent_system_logs(self, n: int = 200) -> List[str]: ...
    def get_recent_denials(self, n: int = 50) -> List[Dict[str, Any]]: ...
    def get_denial(self, trace_id: str) -> Optional[Dict[str, Any]]: ...


@dataclass(frozen=True)
class UiConfig:
    refresh_interval_ms: int = 350
    max_log_entries_displayed: int = 200
    theme: str = "light"
    confirm_on_exit: bool = True

